# Generated by Django 3.1.7 on 2021-04-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, to='users.Association', verbose_name='Groups'),
        ),
    ]
