# Generated by Django 3.1.7 on 2021-04-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210410_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='key',
            field=models.UUIDField(default='17551cd310d34d5584ca76f63a9ae6e9', verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.UUIDField(default='17551cd310d34d5584ca76f63a9ae6e9', verbose_name='Key'),
        ),
    ]
