# Generated by Django 3.1.7 on 2021-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210410_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='key',
            field=models.UUIDField(default='f4eb503fdc614f0986edfbf6156ea6b2', verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.UUIDField(default='f4eb503fdc614f0986edfbf6156ea6b2', verbose_name='Key'),
        ),
    ]
