# Generated by Django 3.1.7 on 2021-04-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210410_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='key',
            field=models.UUIDField(default='02fd352b86f44a4d927055892a5bb7a3', verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.UUIDField(default='02fd352b86f44a4d927055892a5bb7a3', verbose_name='Key'),
        ),
    ]
