# Generated by Django 3.1.5 on 2021-02-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinfoproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='historicalinfoproduct',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='historicalreviewproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='historicalreviewproduct',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='historicaltopmoneyproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='historicaltopmoneyproduct',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='reviewproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='reviewproduct',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='topmoneyproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='topmoneyproduct',
            name='manufacturer',
        ),
    ]
