# Generated by Django 3.1.5 on 2021-02-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210131_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreviewpostestimates',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='historicalreviewpostestimates',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalreviewpostestimates',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='historicaltopmoneypostestimates',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='historicaltopmoneypostestimates',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltopmoneypostestimates',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='infopostestimates',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='infopostestimates',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='reviewpostestimates',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='reviewpostestimates',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='topmoneypostestimates',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='topmoneypostestimates',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='historicalinfopost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='historicalreviewpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='historicaltopmoneypost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='infopost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='topmoneypost',
            name='post',
        ),
        migrations.DeleteModel(
            name='HistoricalInfoPostEstimates',
        ),
        migrations.DeleteModel(
            name='HistoricalReviewPostEstimates',
        ),
        migrations.DeleteModel(
            name='HistoricalTopMoneyPostEstimates',
        ),
        migrations.DeleteModel(
            name='InfoPostEstimates',
        ),
        migrations.DeleteModel(
            name='ReviewPostEstimates',
        ),
        migrations.DeleteModel(
            name='TopMoneyPostEstimates',
        ),
    ]
