# Generated by Django 3.1.5 on 2021-02-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210213_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalaffiliateimage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalaffiliateimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalnormalimage',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='NormalImage',
        ),
        migrations.RemoveField(
            model_name='affiliatelink',
            name='affiliate_tag',
        ),
        migrations.RemoveField(
            model_name='historicalaffiliatelink',
            name='affiliate_tag',
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.affiliatetag', verbose_name='Affiliate Tag'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='category',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='category',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='historicalaffiliatelink',
            name='tag',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.affiliatetag', verbose_name='Affiliate Tag'),
        ),
        migrations.AddField(
            model_name='historicalaffiliateproduct',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='historicalaffiliateproduct',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='historicalinfopost',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='historicalinfopost',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='historicalreviewpost',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='historicalreviewpost',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='historicaltopmoneypost',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='historicaltopmoneypost',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='infopost',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='infopost',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='topmoneypost',
            name='alt_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Alt Tag'),
        ),
        migrations.AddField(
            model_name='topmoneypost',
            name='caption',
            field=models.TextField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.DeleteModel(
            name='AffiliateImage',
        ),
        migrations.DeleteModel(
            name='HistoricalAffiliateImage',
        ),
        migrations.DeleteModel(
            name='HistoricalNormalImage',
        ),
    ]
