# Generated by Django 3.1.5 on 2021-02-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210215_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproduct',
            name='affiliate_program',
        ),
        migrations.RemoveField(
            model_name='reviewproduct',
            name='affiliate_program',
        ),
        migrations.RemoveField(
            model_name='topmoneyproduct',
            name='affiliate_program',
        ),
    ]
