# Generated by Django 3.1.5 on 2021-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210213_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateproduct',
            name='file',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/images/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/images/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='historicalaffiliateproduct',
            name='file',
            field=models.TextField(default='blog/images/default.jpg', max_length=100, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='file',
            field=models.TextField(default='blog/images/default.jpg', max_length=100, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='historicalinfopost',
            name='file',
            field=models.TextField(default='blog/images/default.jpg', max_length=100, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='historicalreviewpost',
            name='file',
            field=models.TextField(default='blog/images/default.jpg', max_length=100, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='historicaltopmoneypost',
            name='file',
            field=models.TextField(default='blog/images/default.jpg', max_length=100, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='infopost',
            name='file',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/images/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='file',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/images/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='topmoneypost',
            name='file',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/images/', verbose_name='File'),
        ),
    ]
