# Generated by Django 3.1.5 on 2021-01-22 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210121_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopostestimates',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='reviewpostestimates',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='topmoneypostestimates',
            name='profit',
        ),
        migrations.AddField(
            model_name='infopostestimates',
            name='monthly_profit',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Profit'),
        ),
        migrations.AddField(
            model_name='reviewpostestimates',
            name='monthly_profit',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Profit'),
        ),
        migrations.AddField(
            model_name='topmoneypostestimates',
            name='monthly_profit',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='infopostestimates',
            name='cost',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='infopostestimates',
            name='monthly_views',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Monthly Views'),
        ),
        migrations.AlterField(
            model_name='reviewpostestimates',
            name='cost',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='reviewpostestimates',
            name='monthly_views',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Monthly Views'),
        ),
        migrations.AlterField(
            model_name='topmoneypostestimates',
            name='cost',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='topmoneypostestimates',
            name='monthly_views',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Monthly Views'),
        ),
    ]
