# Generated by Django 3.1.5 on 2021-01-22 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210121_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopostestimates',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reviewpostestimates',
            name='post',
        ),
        migrations.RemoveField(
            model_name='topmoneypostestimates',
            name='post',
        ),
        migrations.AddField(
            model_name='infopost',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.infopostestimates', verbose_name='Info Post Estimates'),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.reviewpostestimates', verbose_name='Review Post Estimates'),
        ),
        migrations.AddField(
            model_name='topmoneypost',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.topmoneypostestimates', verbose_name='Top Money Post Estimates'),
        ),
    ]
