# Generated by Django 3.1.5 on 2021-02-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210218_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubcategory',
            old_name='post',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='post',
            new_name='category',
        ),
    ]
