# Generated by Django 3.1.5 on 2021-02-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210220_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='historicalinfopost',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='historicalinfoproduct',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='historicalreviewpost',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='historicalreviewproduct',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='historicaltopmoneypost',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='historicaltopmoneyproduct',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='infopost',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='topmoneypost',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='topmoneyproduct',
            name='caption',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
    ]
