# Generated by Django 3.1.5 on 2021-02-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210213_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinfoproduct',
            name='post',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.infopost', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='historicalreviewproduct',
            name='post',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.reviewpost', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='historicaltopmoneyproduct',
            name='post',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.topmoneypost', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='infoproduct',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.infopost', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='reviewproduct',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.reviewpost', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='topmoneyproduct',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.topmoneypost', verbose_name='Post'),
        ),
    ]
