# Generated by Django 3.1.5 on 2021-01-22 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210121_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateproduct',
            name='link',
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.affiliateproduct', verbose_name='Affiliate Product'),
        ),
    ]
