# Generated by Django 3.1.5 on 2021-02-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210213_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinfoproduct',
            old_name='sku_asin',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='historicalreviewproduct',
            old_name='sku_asin',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='historicaltopmoneyproduct',
            old_name='sku_asin',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='infoproduct',
            old_name='sku_asin',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='reviewproduct',
            old_name='sku_asin',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='topmoneyproduct',
            old_name='sku_asin',
            new_name='sku',
        ),
    ]
