# Generated by Django 3.1.5 on 2021-01-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_affiliateimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatelink',
            name='follow',
            field=models.CharField(choices=[('NF', 'No Follow'), ('DF', 'Do Follow')], max_length=10, verbose_name='Follow'),
        ),
        migrations.AlterField(
            model_name='normallink',
            name='follow',
            field=models.CharField(choices=[('NF', 'No Follow'), ('DF', 'Do Follow')], max_length=10, verbose_name='Follow'),
        ),
    ]
