# Generated by Django 3.1.5 on 2021-02-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210227_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='infopost',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='topmoneypost',
            name='tag',
        ),
        migrations.DeleteModel(
            name='HistoricalTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
