# Generated by Django 3.1.5 on 2021-03-03 12:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210228_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinfopost',
            name='outro',
        ),
        migrations.RemoveField(
            model_name='historicalreviewpost',
            name='outro',
        ),
        migrations.RemoveField(
            model_name='infopost',
            name='outro',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='outro',
        ),
        migrations.AddField(
            model_name='historicaltopmoneypost',
            name='intro',
            field=tinymce.models.HTMLField(null=True, verbose_name='Intro'),
        ),
        migrations.AddField(
            model_name='topmoneypost',
            name='intro',
            field=tinymce.models.HTMLField(null=True, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='historicaltopmoneypost',
            name='outro',
            field=tinymce.models.HTMLField(null=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='topmoneypost',
            name='outro',
            field=tinymce.models.HTMLField(null=True, verbose_name='Conclusion'),
        ),
    ]
