# Generated by Django 3.1.5 on 2021-01-22 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210121_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatelink',
            name='anchor_text',
            field=models.CharField(max_length=30, verbose_name='Anchor Text'),
        ),
        migrations.AlterField(
            model_name='normallink',
            name='anchor_text',
            field=models.CharField(max_length=30, verbose_name='Anchor Text'),
        ),
        migrations.CreateModel(
            name='AffiliateTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='Tag')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.affiliateprogram', verbose_name='Affiliate Program')),
            ],
            options={
                'verbose_name': 'Affiliate Tag',
                'verbose_name_plural': 'Affiliate Tags',
            },
        ),
    ]
