# Generated by Django 3.1.5 on 2021-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210303_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinfopost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalreviewpost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaltopmoneypost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='infopost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='topmoneypost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
