# Generated by Django 3.1.5 on 2021-01-31 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210124_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (('lawwwll', 'viewable'),), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
